import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStoreData from "../data/coffeeStore.json";
import axios from "axios";
import fetchCoffeeStore from "../lib/coffee-store";

export async function getStaticProps(context) {
  const coffeeStore = await fetchCoffeeStore();
  return {
    props: { coffeeStore },
  };
}

export default function Home(props) {
  // console.log("props", props);
  const buttonClickHandler = () => {
    console.log("The Banner Button Click");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={"View Store Nearby"}
          buttonClick={buttonClickHandler}
        />
        <div className={styles.heroImage}>
          <Image
            src="/../public/static/hero-image.png"
            width={700}
            height={400}
            alt="hero Image"
          />
        </div>
        {props.coffeeStore.length > 0 && (
          <>
            <h2 className={styles.heading2}>Surat Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStore.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    className={styles.card}
                    imageUrl={
                      coffeeStore.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    alternate={coffeeStore.name}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
